spring:
  main:
    banner-mode: "off"
  jackson:
    mapper:
#      default-view-inclusion: true
    default-property-inclusion: non_empty

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mercury
    username: mercury
    password: password
    initial-size: 5
    max-wait: 10000
    max-active: 20
    max-idle: 10
    test-on-borrow: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  implicit_naming_strategy: jpa
  hbm2ddl.auto: create
  format_sql: false
  show_sql: true

server:
  port: 9090
  contextPath: /api/v1
